### ISSUE TITLE
Django 1.10's BaseCommand no longer has option_list.

### ISSUE THREAD

**Issue by ldng** [django-waffle/django-waffle#199]
./manage.py waffle_switch --help

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File ".pyenv/versions/project/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File ".pyenv/versions/project/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".pyenv/versions/project/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File ".pyenv/versions/project/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File ".pyenv/versions/3.5.1/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File ".pyenv/versions/project/lib/python3.5/site-packages/waffle/management/commands/waffle_switch.py", line 10, in <module>
    class Command(BaseCommand):
  File ".pyenv/versions/project/lib/python3.5/site-packages/waffle/management/commands/waffle_switch.py", line 11, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

**Comment by jsocol** [comment]
Closing in favor of #200

**Comment by thallada** [comment]
Any update on this? Django ended extended support of 1.9 two months ago...

**Comment by clintonb** [comment]
@ldng @jsocol the proper method to add options is to use the `add_arguments` method. See https://docs.djangoproject.com/en/1.8/howto/custom-management-commands/#custom-commands-options.
