### ISSUE TITLE
Django 1.10 middleware failing: TypeError: object.__new__() takes no parameters

### ISSUE THREAD

**Issue by mokutsu** [django-waffle/django-waffle#241]
Hi, I've been trying to get the newest version of django-waffle working with Django 1.10, and am continuing to get the typeerror below related to the middleware.  I've tried turning off and on all of my middleware and have narrowed this error down to django-waffle. I noticed this is the same issue as https://github.com/jsocol/django-waffle/issues/232 i think.  Any ideas?  Thanks very much!

Django version: 1.10.0
Django-waffle: 0.11.1
Python: version 2.7.3

```
Traceback (most recent call last):
  File "/home/webdev/websites/polaris/pysrc/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django_extensions/management/commands/runserver_plus.py", line 217, in handle
    self.inner_run(options)
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django_extensions/management/commands/runserver_plus.py", line 272, in inner_run
    handler = get_internal_wsgi_application()
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 46, in get_internal_wsgi_application
    return get_wsgi_application()
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 153, in __init__
    self.load_middleware()
  File "/var/virtualenvs/polaris/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: object.__new__() takes no parameters
```

**Comment by do3cc** [comment]
Hi, you are using the latest released version of waffle. It contains the old style middleware, you try to use it as the new style middleware.
Support for new style middleware has only been added on github but no release has been cut. 
See #240

**Comment by browniebroke** [comment]
For those who are interested, I'm using this workaround to use new style middleware with the PyPI released version:
```python
from django.utils.deprecation import MiddlewareMixin
from waffle.middleware import WaffleMiddleware


class WaffleNewStyleMiddleware(MiddlewareMixin, WaffleMiddleware):
    pass
```

**Comment by wx2228** [comment]
is this project still under development? this fix is still not released and the last commit is nearly 5 months ago

**Comment by chris-griffin** [comment]
I think this can be closed now given the new release

**Comment by jsocol** [comment]
Agreed!
